from PikaObj import *


class lv_obj(TinyObj):
    pass


class arc(lv_obj):
    def __init__(self, parent: lv_obj): ...
    def set_end_angle(angle: int): ...
    def set_size(size_x: int, size_y: int): ...
    def center(self): ...


def scr_act() -> lv_obj: ...
