from PikaObj import *


class lv_obj(TinyObj):
    def center(self): ...
    def set_size(size_x: int, size_y: int): ...


class arc(lv_obj):
    def __init__(self, parent: lv_obj): ...
    def set_end_angle(self, angle: int): ...
    def set_bg_angles(self, start: int, end: int): ...
    def set_angles(self, start: int, end: int): ...


class bar(lv_obj):
    def __init__(self, parent: lv_obj): ...
    def set_value(value: int, anim: int): ...


def scr_act() -> lv_obj: ...
